### ISSUE TITLE
can't get through initial setup

### ISSUE THREAD

**Issue by zebralight** [yuya373/emacs-slack#225]
I noticed that when I try to run slack-register-team to get the token, I get the following error: "Symbol's function definition is void: slack-ws-close". I tried looking up this message to no avail.

**Comment by mgudemann** [comment]
same here, unfortunately. Are there any news on this

**Comment by mgudemann** [comment]
@zebralight for me, it is resolved via starting `IELM` and do a `(require 'slack)`
I also had to change the `http://localhost:8080/` to `http://localhost:8080` for redirect URLs

**Comment by jtmoulia** [comment]
@zebralight are you using a package lazy loader, e.g. [use-package](https://github.com/jwiegley/use-package) (e.g. spacemacs uses use-package).

If so, you need to ensure that calling `slack-register-team` actually loads the package.

**Comment by winmillwill** [comment]
IIUC, doing a `(require 'slack)` is meant to address this issue, but it still persists after I do that:

```
Contacting host: slack.com:443
Your Token is added to kill ring.
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect cerberus-xxxx.lb.slack-msgs.com:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...done
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
[2018-04-12 08:26:23] [warn] [Pantheon] Slack Websocket Try To Reconnect 1/360
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect cerberus-xxxx.lb.slack-msgs.com:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...done
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
[2018-04-12 08:26:41] [warn] [Pantheon] Slack Websocket Try To Reconnect 2/360
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect cerberus-xxxx.lb.slack-msgs.com:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...done
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
[2018-04-12 08:26:59] [warn] [Pantheon] Slack Websocket Try To Reconnect 3/360
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com’...failed
Opening TLS connection with ‘gnutls-cli --x509cafile nil -p 443 cerberus-xxxx.lb.slack-msgs.com --protocols ssl3’...failed
Opening TLS connection with ‘openssl s_client -connect cerberus-xxxx.lb.slack-msgs.com:443 -no_ssl2 -ign_eof’...done
Opening TLS connection to ‘cerberus-xxxx.lb.slack-msgs.com’...done
error in process filter: websocket-outer-filter: Invalid HTTP header sent
error in process filter: Invalid HTTP header sent
[2018-04-12 08:27:19] [warn] [Pantheon] Slack Websocket Try To Reconnect 4/360
```
